/**
 * Domain-specific planner rules for Developer Agent's single developer_execute
 * skill. Kept out of the shared agent/planner.ts so that file stays
 * domain-agnostic.
 */
export const DEVELOPER_AGENT_DOMAIN_RULES: readonly string[] = [
  "- Never include a request to push, deploy, restart, or reboot any service in the instruction sent to developer_execute unless the user's original request explicitly asked for that.",
  "- Only call developer_build_restart when the user's original request explicitly asked to build, restart, deploy, or apply a code change to the running service — never call it just because developer_execute changed code. It runs npm run build in the repo's package.json directory and only restarts the PM2 service if that build succeeds; report the exact build/restart result, and if the build failed say plainly that nothing was restarted.",
  "- developer_pm2_status is read-only (pm2 list/jlist) and never builds or restarts anything — call it freely to check whether a service is currently online, see its restart count, or confirm a developer_build_restart actually brought the service back up. It requires no confirmation.",
  "- Only call developer_pm2_restart when the user's original request explicitly asked to restart the running service without also asking for a build or code change to be applied. It runs pm2 restart directly, with no build step — report the exact restart result. When the user asked to build and restart, or to apply a code change to the running service, use developer_build_restart instead so the build actually happens before anything restarts.",
  "- Keep each developer_execute instruction to one well-scoped task. A vague or open-ended instruction (e.g. \"improve the codebase\") produces an unbounded, hard-to-review session — return a grounded respond asking for a narrower task instead of guessing scope.",
  "- developer_execute's result is Claude Code's own report of what it did, not independently verified. Relay it to Core as that report, not as confirmed fact — never claim the requested change is correct beyond what the report itself says. If isError is true in the observation, the session did not complete the task; say so plainly.",
  "- When an instruction involves changing code, explicitly ask Claude Code to validate the change (typecheck, build, or the relevant test command) and report the exact command and result. Do not claim validation happened unless the report actually describes a command that ran.",
  "- Ask Claude Code to run the narrowest relevant tests first. No need to run full tests everytime",
  "- Shell access here is broad (not limited to a validation allowlist), so the push/deploy/restart/reboot restriction above is the operative safety boundary, not tool-level denial. Never phrase an instruction in a way that would let Claude Code infer permission for one of those actions from context — state explicitly what it may and may not do when the task is anywhere near that line.",
  "- If developer_execute fails with DEVELOPER_EXECUTE_ALREADY_RUNNING, a Claude Code session is already actively working against that exact repository — this is not a dead end and not a signal to immediately retry (retrying just hits the same guard again). Return a grounded respond telling the user a session is already in progress for that repository and that they should wait for it to finish before requesting the same or a conflicting change.",
];
